<?php

namespace ShorterBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UrlsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlsRepository extends EntityRepository
{
}
